#include "../config.h"
#include "../../include/global.h"
#include "../../include/constants/trainer_classes.h"
#include "../../include/constants/songs.h"
#include "../../include/constants/species.h"
/*
music_tables.c
	set up music for each trainer class

tables to edit:
	gClassBasedTrainerEncounterBGM
	gClassBasedBattleBGM
	gWildSpeciesBasedBattleBGM
	gRandomBattleMusicOptions

*/

#ifdef ENCOUNTER_MUSIC_BY_CLASS
const u16 gClassBasedTrainerEncounterBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_YOUNGSTER] = BGM_EYE_BOY,
	[CLASS_BUG_CATCHER] = BGM_EYE_BOY,
	[CLASS_LASS] =  BGM_EYE_GIRL,
	[CLASS_SAILOR] = BGM_EYE_BOY,
	[CLASS_CAMPER] = BGM_EYE_BOY,
	[CLASS_PICNICKER] =  BGM_EYE_GIRL,
	[CLASS_POKEMANIAC] = BGM_EYE_CREEPY,
	[CLASS_SUPER_NERD] = BGM_EYE_CREEPY,
	[CLASS_HIKER] = BGM_EYE_BOY,
	[CLASS_BIKER] = BGM_EYE_BOY,
	[CLASS_BURGLAR] = BGM_EYE_CREEPY,
	[CLASS_ENGINEER] = BGM_EYE_BOY,
	[CLASS_FISHERMAN] = BGM_EYE_BOY,
	[CLASS_SWIMMER_M] = BGM_EYE_BOY,
	[CLASS_CUE_BALL] = BGM_EYE_BOY,
	[CLASS_GAMBLER] = BGM_EYE_BOY,
	[CLASS_BEAUTY] =  BGM_EYE_GIRL,
	[CLASS_SWIMMER_F] =  BGM_EYE_GIRL,
	[CLASS_PSYCHIC] = BGM_EYE_BOY,
	[CLASS_ROCKER] = BGM_EYE_BOY,
	[CLASS_JUGGLER] = BGM_EYE_BOY,
	[CLASS_TAMER] = BGM_EYE_BOY,
	[CLASS_BIRD_KEEPER] = BGM_EYE_BOY,
	[CLASS_BLACK_BELT] = BGM_EYE_BOY,
	[CLASS_RIVAL] = BGM_RIVAL,
	[CLASS_SCIENTIST] = BGM_EYE_BOY,
	[CLASS_BOSS] = BGM_EYE_BOY,
	[CLASS_LEADER] = BGM_EYE_BOY,
	[CLASS_TEAM_ROCKET] = BGM_EYE_CREEPY,
	[CLASS_COOLTRAINER] = BGM_EYE_BOY,
	[CLASS_ELITE_4] = BGM_EYE_BOY,
	[CLASS_GENTLEMAN] = BGM_EYE_BOY,
	[CLASS_RIVAL_2] = BGM_RIVAL,
	[CLASS_CHAMPION] = BGM_EYE_BOY,
	[CLASS_CHANNELER] = BGM_EYE_CREEPY,
	[CLASS_TWINS] =  BGM_EYE_GIRL,
	[CLASS_COOL_COUPLE] = BGM_EYE_BOY,
	[CLASS_YOUNG_COUPLE] = BGM_EYE_BOY,
	[CLASS_CRUSH_KIN] = BGM_EYE_BOY,
	[CLASS_SIS_AND_BRO] =  BGM_EYE_GIRL,
	[CLASS_PKMN_PROF] = BGM_EYE_BOY,
	[CLASS_PLAYER] = BGM_EYE_BOY,
	[CLASS_CRUSH_GIRL] =  BGM_EYE_GIRL,
	[CLASS_TUBER] = BGM_EYE_BOY,
	[CLASS_PKMN_BREEDER] = BGM_EYE_BOY,
	[CLASS_PKMN_RANGER] = BGM_EYE_BOY,
	[CLASS_AROMA_LADY] =  BGM_EYE_GIRL,
	[CLASS_RUIN_MANIAC] = BGM_EYE_BOY,
	[CLASS_LADY] =  BGM_EYE_GIRL,
	[CLASS_PAINTER] =  BGM_EYE_GIRL,
};
#endif

const u16 gClassBasedBattleBGM[NUM_TRAINER_CLASSES] =
{
	[CLASS_PKMN_TRAINER_1] = BGM_HGSS_CHAMPION,
	[CLASS_CHAMPION] = BGM_HGSS_CHAMPION,
	[CLASS_LEADER] = BGM_HGSS_KANTO_GYM_LEADER,
	[CLASS_ELITE_4] = BGM_HGSS_KANTO_GYM_LEADER,
};

const u16 gWildSpeciesBasedBattleBGM[] =
{
	[SPECIES_ENTEI] = BGM_HGSS_BATTLE_ENTEI,
	[SPECIES_RAIKOU] = BGM_HGSS_BATTLE_RAIKOU,
	[SPECIES_SUICUNE] = BGM_HGSS_BATTLE_SUICUNE,
	[SPECIES_HO_OH] = BGM_HGSS_BATTLE_HO_OH,
	[SPECIES_LUGIA] = BGM_HGSS_BATTLE_LUGIA,
	[SPECIES_GROUDON] = BGM_HGSS_ANCIENT_LEGEND,
	[SPECIES_KYOGRE] = BGM_HGSS_ANCIENT_LEGEND,
	[SPECIES_RAYQUAZA] = BGM_HGSS_ANCIENT_LEGEND,

	// [SPECIES_JIRACHI] = BGM_CUSTOM_NOT_IMPLEMENTED,
	[SPECIES_DIALGA] = BGM_HGSS_ANCIENT_LEGEND,
};

const u16 gRandomBattleMusicOptions[] =
{
	BGM_HGSS_WILD_KANTO,
	BGM_HGSS_KANTO_TRAINER,
	BGM_HGSS_KANTO_GYM_LEADER,
	BGM_HGSS_CHAMPION,
	BGM_HGSS_BATTLE_ENTEI,
	BGM_HGSS_ANCIENT_LEGEND,
	BGM_HGSS_JOHTO_GYM_LEADER,
};

const u8 gRandomBattleMusicOptionsLength = ARRAY_COUNT(gRandomBattleMusicOptions);
const u16 gWildSpeciesBasedBattleBGMLength = ARRAY_COUNT(gWildSpeciesBasedBattleBGM);
